export interface POPTemplate {
  id: string;
  title: string;
  category: string;
  objective: string;
  applicationField: string;
  definitions: string;
  responsible: string;
  materials: string;
  epi?: string;
  riscos?: string;
  procedure: string;
  monitoring: string;
  reviewFrequency: string;
  references: string;
}

export const POP_TEMPLATES: POPTemplate[] = [
  {
    id: 'dispensacao',
    title: 'Dispensação de Medicamentos e Atenção Farmacêutica',
    category: 'Assistência',
    objective: 'Padronizar o processo de dispensação para garantir a entrega do medicamento correto, na dose correta, ao paciente correto, acompanhado das informações necessárias para o uso racional e seguro, minimizando erros de medicação e promovendo a adesão terapêutica conforme a RDC 44/2009.',
    applicationField: 'Balcão de atendimento e área de dispensação da drogaria.',
    definitions: 'Dispensação: Ato farmacêutico de fornecimento de medicamentos e orientação técnica. Uso Racional: Uso adequado às necessidades clínicas. Intercâmbio: Substituição técnica do medicamento de referência pelo genérico correspondente (Lei 9.787/99).',
    responsible: 'Farmacêutico (atividades clínicas e supervisão) e Auxiliares/Balconistas capacitados (atividades operacionais).',
    materials: 'Prescrição médica original, Sistema de Gestão (SNGPC), Etiquetas de orientação, Embalagens de entrega, Álcool 70% para higienização das mãos, Guia de Intercâmbio ANVISA.',
    epi: 'Avental branco limpo, máscara (em caso de sintomas respiratórios do paciente), crachá de identificação.',
    riscos: 'Troca de medicamentos, erro de dosagem, reações adversas graves, automedicação induzida.',
    procedure: '1. ACOLHIMENTO E RECEPÇÃO:\n- Recepcionar o paciente/cliente com cortesia e profissionalismo.\n- Solicitar a prescrição médica e verificar se a mesma é original, legível, sem rasuras e dentro do prazo de validade (conforme a categoria do medicamento).\n- Conferir os dados obrigatórios: Nome completo do paciente, nome do medicamento (DCB ou Comercial), concentração, forma farmacêutica, posologia, duração do tratamento, data de emissão, assinatura e carimbo do prescritor com número do registro profissional (CRM/CRO/RMS).\n\n2. ANÁLISE TÉCNICO-FARMACÊUTICA:\n- O Farmacêutico deve avaliar a adequação da terapia: Dose, dosagem, via de administração e frequência de uso.\n- Verificar possíveis interações medicamentosas (fármaco-fármaco, fármaco-alimento), duplicidade terapêutica ou contraindicações baseadas no perfil do paciente (idade, peso, gravidez, lactação).\n- Em caso de dúvidas ou erros na prescrição, o farmacêutico deve entrar em contato com o prescritor para esclarecimentos ANTES da dispensação.\n- Realizar o intercâmbio por medicamento genérico, se aplicável, conforme a Lei 9.787/99, educando o paciente sobre a equivalência e economia.\n\n3. SEPARAÇÃO E CONFERÊNCIA RIGOROSA:\n- Selecionar o medicamento no estoque utilizando a técnica FEFO (Primeiro que Vence, Primeiro que Sai).\n- Conferir triplamente (Receita vs. Caixa vs. Sistema): Nome, Dosagem, Lote, Data de Validade e Forma Farmacêutica.\n- No caso de medicamentos controlados (Portaria 344/98) ou Antimicrobianos (RDC 20/2011), realizar a retenção da via e preenchimento dos dados do comprador.\n\n4. ORIENTAÇÃO AO PACIENTE (ATENÇÃO FARMACÊUTICA):\n- Explicar detalhadamente: Como tomar (jejum, com comida), horários exatos para manter a concentração plasmática sanguínea.\n- Instruir sobre o armazenamento correto no domicílio (evitar cozinha e banheiro devido ao calor e umidade).\n- Informar sobre os principais efeitos adversos e o que fazer caso ocorram.\n- Utilizar o método "Show-me" (Pedir para o paciente explicar como ele entendeu que deve usar) para garantir a compreensão total.\n- Entregar folder ou bula simplificada se o paciente apresentar dificuldades de leitura.\n\n5. REGISTRO E FINALIZAÇÃO:\n- Registrar a saída no sistema informatizado para atualização do inventário e controle fiscal.\n- Carimbar, datar e assinar o verso da receita para validar a dispensação efetuada.\n- Organizar as receitas retidas para posterior escrituração no SNGPC.\n- Entregar o medicamento em embalagem adequada e higienizada.',
    monitoring: 'Monitoramento semanal: Auditoria de 20% das receitas dispensadas no período para verificar conformidade dos registros. Registro de erros de dispensação (Near Miss) em planilha específica de qualidade.',
    reviewFrequency: 'Anual ou em caso de mudanças na legislação sanitária.',
    references: 'RDC 44/2009 (ANVISA), Lei 13.021/2014, Portaria 344/98, RDC 20/2011.'
  },
  {
    id: 'psicotropicos',
    title: 'Controle e Dispensação de Medicamentos sob Controle Especial (Portaria 344/98)',
    category: 'Controlados',
    objective: 'Estabelecer normas técnicas rigorosas para o recebimento, armazenamento, escrituração e dispensação de substâncias e medicamentos sujeitos a controle especial, prevenindo o uso indevido e atendendo plenamente à legislação federal.',
    applicationField: 'Armário de segurança de controlados, balcão de atendimento e computador do RT.',
    definitions: 'SNGPC: Sistema Nacional de Gerenciamento de Produtos Controlados. Notificação de Receita: Documento padronizado que autoriza a dispensação de substâncias das listas A, B e C3.',
    responsible: 'Farmacêutico Responsável Técnico (RT) ou Substituto. A guarda das chaves e senhas é de responsabilidade exclusiva do farmacêutico.',
    materials: 'Armário de aço com fechadura robusta, Livro de Registro ou Sistema SNGPC, Software homologado, Carimbos de identificação, Computador com Certificado Digital.',
    epi: 'Avental branco, identificação visível.',
    riscos: 'Desvio de substâncias, uso recreativo indevido, penalidades criminais por erro de escrituração.',
    procedure: '1. RECEBIMENTO TÉCNICO E CONFERÊNCIA:\n- O recebimento deve ser realizado prioritariamente pelo Farmacêutico ou sob sua supervisão direta.\n- Conferir a Nota Fiscal com o produto físico, validando Lote, Data de Validade e número de registro MS.\n- Verificar se a distribuidora possui autorização especial válida para o transporte/venda desses itens.\n- O produto deve ser movido IMEDIATAMENTE para a área segura.\n\n2. ARMAZENAMENTO E SEGURANÇA:\n- Manter 100% dos itens das listas da Portaria 344/98 sob chave em armário resistente ou sala trancada de acesso restrito.\n- Organizar por Lista (A1, A2, B1, B2, C1, C2, C3, C4, C5) e por ordem alfabética de princípio ativo.\n- Realizar conferência de estoque diária no final de cada expediente.\n\n3. CONFERÊNCIA DAS RECEITAS E NOTIFICAÇÕES:\n- Analisar a Notificação de Receita (Correta conforme a lista: Amarela para A, Azul para B, Branca para C1).\n- Verificar validade territorial (receitas de outros estados devem ser acompanhadas de justificativa e autenticadas se necessário).\n- Conferir se a quantidade prescrita não ultrapassa o limite de tratamento (Ex: 30 dias para B1, 6 meses para C1 anticonvulsivantes).\n- Exigir identificação original do comprador e preencher todos os campos do verso da receita à caneta.\n\n4. ESCRITURAÇÃO ELETRÔNICA (SNGPC):\n- Realizar a baixa do medicamento no sistema informatizado no ato da venda.\n- Gerar e transmitir o arquivo XML para a ANVISA semanalmente (ou conforme prazo estabelecido pela VISA local).\n- Arquivar o comprovante de transmissão de dados (aceite) junto à documentação fiscal.\n\n5. BALANÇOS E ARQUIVAMENTO:\n- Elaborar trimestralmente o Balanço de Substâncias Psicotrópicas (BSPO) e o Balanço de Medicamentos Psicotrópicos (BMN).\n- Manter as receitas e notificações arquivadas por no mínimo 2 anos, em ordem cronológica e por lista.',
    monitoring: 'Inventário físico total mensal. Auditoria diária de campo "comprador" nas receitas retidas. Verificação semanal do status de transmissão no SNGPC.',
    reviewFrequency: 'Anual ou sempre que houver alteração nas listas da Portaria 344/98.',
    references: 'Portaria SVS/MS nº 344/98, RDC nº 22/2011, RDC nº 58/2007.'
  },
  {
    id: 'recebimento',
    title: 'Recebimento de Mercadorias e Conferência de Qualidade',
    category: 'Logística',
    objective: 'Padronizar a entrada de medicamentos e produtos para saúde, garantindo que apenas itens em conformidade com as especificações técnicas, fiscais e de qualidade sejam incorporados ao estoque da drogaria.',
    applicationField: 'Área de recebimento, conferência e quarentena.',
    definitions: 'Quarentena: Área delimitada para produtos que aguardam decisão do RT para liberação ou devolução. Termolábil: Medicamento que exige temperatura controlada rigorosa (2°C a 8°C).',
    responsible: 'Almoxarife, Conferente e Farmacêutico Responsável Técnico.',
    materials: 'Notas Fiscais (DANFE), Termômetro de mira laser, Termohigrômetro, Estilete, Etiquetas de identificação de quarentena/divergência.',
    epi: 'Luvas de proteção (para abertura de caixas), sapatos fechados, avental.',
    riscos: 'Recebimento de produtos falsificados, avariados ou fora da temperatura ideal (termolábeis). Acidentes perfurocortantes em embalagens violadas.',
    procedure: '1. PROCEDIMENTO DE CHEGADA E TRIAGEM:\n- Verificar se a mercadoria é destinada ao CNPJ da drogaria e se o número de volumes coincide com a Nota Fiscal.\n- Observar as condições de higiene do veículo de transporte e do entregador.\n- Recusar volumes com sinais de violação, umidade extrema ou que tenham sido expostos a substâncias tóxicas.\n\n2. CONFERÊNCIA DE TERMOLÁBEIS (PRIORIDADE ABSOLUTA):\n- Medicamentos de geladeira devem ser conferidos IMEDIATAMENTE após a chegada.\n- Utilizar o termômetro laser para medir a temperatura interna da caixa térmica sem abri-la totalmente (se possível) e após a abertura.\n- A temperatura deve estar rigorosamente entre 2°C e 8°C. Registrar a temperatura e o horário da entrega no canhoto da nota e na planilha específica.\n\n3. CONFERÊNCIA TÉCNICA E FISCAL:\n- Abrir os volumes e confrontar cada item físico com a Nota Fiscal: Nome, Fabricante, Lote, Quantidade e Data de Validade.\n- Verificar se o Registro MS está impresso na embalagem secundária.\n- Observar o aspecto físico: Integridade dos lacres, ausência de pó no interior das caixas (sinal de quebra), integridade do selo de segurança (raspadinha).\n\n4. DESTINAÇÃO E QUARENTENA:\n- Itens aprovados: Liberar para etiquetagem e entrada no sistema pelo setor administrativo.\n- Itens reprovados (Avaria, validade curta, erro de lote): Colocar na área de QUARENTENA devidamente sinalizada.\n- Emitir a Nota de Devolução imediatamente ou notificar o setor de compras sobre a divergência.',
    monitoring: 'Verificação mensal do relatório de faltas e avarias identificadas no recebimento. Auditoria semanal de entrada de lotes no sistema vs nota fiscal.',
    reviewFrequency: 'Anual ou conforme normas de Boas Práticas de Distribuição.',
    references: 'RDC 44/2009, RDC 304/2019 (Distribuição e Armazenagem).'
  },
  {
    id: 'armazenamento',
    title: 'Armazenamento, Conservação e Preservação do Estoque',
    category: 'Logística',
    objective: 'Garantir que os produtos farmacêuticos e para saúde sejam mantidos em condições ambientais ideais, preservando sua eficácia, segurança e qualidade durante todo o período de estocagem.',
    applicationField: 'Almoxarifado, prateleiras de exposição e áreas de venda.',
    definitions: 'FEFO: First Expire, First Out (Primeiro que Vence, Primeiro que Sai). Temperatura Ambiente: 15°C a 30°C. Umidade Relativa: 40% a 70%.',
    responsible: 'Farmacêutico RT, Almoxarife e Equipe de Reposição.',
    materials: 'Prateleiras laváveis (aço ou plástico), Paletes, Termohigrômetros calibrados, Ar-condicionado, Geladeira técnica.',
    epi: 'Sapatos fechados com solado antiderrapante, luvas de algodão para manuseio de caixas pesadas.',
    riscos: 'Degradação por calor/umidade excessiva, queda de produtos de altura, avarias por empilhamento incorreto.',
    procedure: '1. ORGANIZAÇÃO E SETORIZAÇÃO ESTRUTURADA:\n- Medicamentos de Prescrição (Éticos): Por ordem alfabética de Princípio Ativo (DCB).\n- Medicamentos Similares: Por ordem alfabética de Nome Comercial.\n- Medicamentos Isentos de Prescrição (MIPs): Organizar por indicação terapêutica para auxiliar o cliente (Ex: Sist. Digestivo, Analgésicos).\n- Produtos para Saúde e Perfumaria: Setor separados dos medicamentos.\n\n2. REGRAS DE EMPILHAMENTO E CIRCULAÇÃO:\n- Manter distância mínima de 10cm do piso (paletes), 15cm das paredes e 50cm do teto para permitir a ventilação e limpeza.\n- NUNCA armazenar produtos diretamente no chão.\n- Respeitar o limite de empilhamento vertical indicado na caixa externa pelo fabricante.\n\n3. MONITORAMENTO AMBIENTAL:\n- Realizar a leitura da temperatura e umidade 02 vezes ao dia (início da manhã e final da tarde).\n- Registrar as variações na Planilha de Controle de Temperatura e Umidade Ambiente.\n- Em caso de temperatura superior a 30°C, ligar o sistema de climatização forçada imediatamente.\n\n4. GESTÃO DE VALIDADE (SISTEMA PVPS):\n- Organizar o estoque de modo que o item com validade mais próxima esteja sempre à frente para ser vendido primeiro.\n- Identificar itens com vencimento para 6 meses com etiqueta de alerta (Amarela).',
    monitoring: 'Inventário rotativo diário de 1 corredor. Inspeção semanal das condições de limpeza das prateleiras. Calibração anual dos termohigrômetros.',
    reviewFrequency: 'Anual.',
    references: 'RDC 44/2009, Guia de Estabilidade de Fármacos da ANVISA.'
  },
  {
    id: 'higienizacao',
    title: 'Higienização e Limpeza das Instalações e Equipamentos',
    category: 'Sanitário',
    objective: 'Estabelecer rotinas rigorosas de higienização para assegurar um ambiente de trabalho livre de contaminantes, garantindo a biossegurança dos pacientes e a integridade dos produtos farmacêuticos, em conformidade com as Boas Práticas Farmacêuticas.',
    applicationField: 'Todas as dependências físicas da drogaria (área de vendas, estoque, sala de serviços, banheiros e refeitório).',
    definitions: 'Sanitização: Redução de microrganismos a níveis seguros por meio de agentes físicos ou químicos. Limpeza Úmida: Técnica que utiliza água e detergente sem suspensão de partículas.',
    responsible: 'Equipe de Limpeza ou funcionários designados, sob supervisão e responsabilidade técnica do Farmacêutico.',
    materials: 'Detergente neutro, Álcool 70% (solução), Hipoclorito de Sódio a 1% (para pisos), Luvas de proteção de borracha, Máscaras descartáveis, Panos de limpeza em cores distintas (para evitar contaminação cruzada), Baldes graduados.',
    epi: 'Luvas de borracha resistente, avental impermeável, botas antiderrapantes, máscara descartável.',
    riscos: 'Quedas em piso molhado, dermatites por contato químico, ingestão acidental de saneantes.',
    procedure: '1. CRONOGRAMA DE FREQUÊNCIA:\n- ÁREAS COMUNS (Piso, Balcões, Banheiros): Limpeza diária e sempre que necessário.\n- ÁREAS TÉCNICAS (Balcão de dispensação, Prateleiras): Limpeza diária e pesada quinzenal.\n- EQUIPAMENTOS (Geladeira, Balanças): Limpeza mensal ou conforme cronograma de manutenção.\n\n2. TÉCNICA DE LIMPEZA (SENTIDO ÚNICO):\n- Iniciar a limpeza sempre da área menos contaminada para a mais contaminada.\n- Realizar a limpeza de cima para baixo (teto, paredes, prateleiras e, por último, o piso).\n- Utilizar a técnica de "duplo balde": um com solução de limpeza e outro com água limpa para enxágue do pano.\n\n3. HIGIENIZAÇÃO DE SUPERFÍCIES DE CONTATO:\n- Aplicar Álcool 70% por fricção em balcões de atendimento por no mínimo 3 vezes ou até a secagem completa do produto.\n- Limpar prateleiras de medicamentos quinzenalmente, retirando os produtos para evitar acúmulo de pó nas embalagens.\n\n4. LIMPEZA DE PISOS E RALOS:\n- Realizar a varredura úmida (NUNCA usar vassoura seca para não suspender poeira).\n- Aplicar solução de Hipoclorito de Sódio 1% nos banheiros e áreas de circulação.\n- Ralos devem ser higienizados diariamente e mantidos com grelhas fechadas.\n\n5. REGISTRO DE EXECUÇÃO:\n- Após a conclusão de cada tarefa, o executor deve registrar a atividade na Planilha de Registro de Limpeza, indicando data, hora e assinatura.',
    monitoring: 'Inspeção visual diária pelo Farmacêutico RT. Auditoria semanal do preenchimento das planilhas de registro de higienização.',
    reviewFrequency: 'Anual ou em caso de surtos epidêmicos ou mudanças estruturais.',
    references: 'RDC 44/2009 (ANVISA), Manual de Limpeza e Desinfecção de Superfícies (ANVISA), NR-32.'
  },
  {
    id: 'injetaveis',
    title: 'Aplicação de Medicamentos Injetáveis (Via Intramuscular e Subcutânea)',
    category: 'Serviços',
    objective: 'Padronizar a técnica de aplicação de injetáveis no consultório farmacêutico, garantindo a segurança biológica do paciente, a eficácia do tratamento e a correta destinação dos perfurocortantes em conformidade com as diretrizes do CFF e ANVISA.',
    applicationField: 'Sala de Serviços Farmacêuticos / Sala de Aplicação.',
    definitions: 'Antissepsia: Procedimento de redução de carga microbiana na pele íntegra por agente químico. Vias: IM (Intramuscular), SC (Subcutânea).',
    responsible: 'Farmacêutico devidamente habilitado ou profissional de saúde legalmente autorizado sob supervisão do RT.',
    materials: 'Prescrição médica original, Medicamento, Seringas e agulhas estéreis (tamanhos conforme via/paciente), Algodão hidrófilo, Álcool 70%, Luvas de procedimento, Caixa coletora de perfurocortantes (Descarpack).',
    epi: 'Luvas de procedimento, jaleco branco, máscara descartável (se necessário), óculos de proteção.',
    riscos: 'Acidentes perfurocortantes, contaminação biológica, reações anafiláticas graves no paciente.',
    procedure: '1. AVALIAÇÃO INICIAL E CONFERÊNCIA:\n- Exigir a apresentação da prescrição médica original, legível e dentro da validade.\n- Perguntar ao paciente sobre histórico de alergias e conferir se o medicamento é o correto (9 certos da medicação).\n- Higienizar as mãos seguindo o protocolo de higienização das mãos.\n\n2. PREPARO DO MATERIAL E ASPIRAÇÃO:\n- Abrir o invólucro da seringa e agulha na frente do paciente.\n- Realizar a antissepsia do gargalo da ampola ou frasco-ampola com álcool 70%.\n- Aspirar o medicamento evitando a formação de bolhas de ar. Se houver bolhas, retirá-las suavemente.\n- Se o medicamento for oleoso ou pó para reconstituição, homogeneizar conforme orientação do fabricante.\n- Trocar a agulha de aspiração por uma agulha nova própria para a aplicação (Ex: 30x7 ou 25x7 para IM adulto), visando o conforto do paciente.\n\n3. TÉCNICA DE APLICAÇÃO (EX: INTRAMUSCULAR):\n- Identificar o músculo alvo (Ventro-glúteo idealmente, ou Vasto lateral/Deltóide dependendo do volume).\n- Realizar a antissepsia do local em sentido único com algodão embebido em álcool 70%.\n- Inserir a agulha em ângulo de 90° (para IM), aspirar o êmbolo para verificar se não houve punção de vaso sanguíneo.\n- Aplicar o líquido de forma lenta e constante. Retirar a agulha com movimento rápido.\n- Aplicar leve pressão no local com algodão seco. NÃO massagear caso o medicamento não permita (Ex: Insulinas, Heparinas).\n\n4. PÓS-PROCEDIMENTO E REGISTRO:\n- Descartar agulha e seringa IMEDIATAMENTE no Descarpack sem reencapar.\n- Preencher o Livro de Registro de Injetáveis (Data, Nome, Medicamento, Lote, Validade, Prescritor).\n- Emitir a Declaração de Serviço Farmacêutico (DSF) e entregar ao paciente.',
    monitoring: 'Auditoria mensal do Livro de Injetáveis vs. Receitas arquivadas. Verificação diária da integridade e nível de preenchimento do coletor de perfurocortantes.',
    reviewFrequency: 'Anual ou conforme novas diretrizes de segurança do paciente.',
    references: 'RDC 44/2009, Resoluções CFF nº 499/2008 e nº 658/2018.'
  },
  {
    id: 'pgrss',
    title: 'Plano de Gerenciamento de Resíduos de Serviços de Saúde (PGRSS)',
    category: 'Ambiental',
    objective: 'Estabelecer os procedimentos para o manejo correto dos resíduos gerados na drogaria, desde a segregação na fonte até a disposição final, visando minimizar os impactos ambientais e proteger a saúde pública.',
    applicationField: 'Todas as áreas de geração de lixo e abrigo externo.',
    definitions: 'Segregação: Separação dos resíduos no momento e local de sua geração. Conforme RDC 222/2018.',
    responsible: 'Farmacêutico Responsável Técnico e Empresa de Coleta Especializada.',
    materials: 'Sacos brancos leitosos (Grupo A), Sacos pretos (Grupo D), Contentores rígidos para perfurocortantes (Grupo E), Recipientes específicos para químicos (Grupo B).',
    epi: 'Luvas resistentes de borracha ou nitrílica, sapatos fechados, avental de proteção.',
    riscos: 'Perfurações com agulhas infectadas, contaminação ambiental e riscos biológicos diversos.',
    procedure: '1. SEGREGAÇÃO RIGOROSA NA FONTE:\n- GRUPO A (Biológicos): Gazes, algodão sujo, luvas contaminadas. Descartar em saco branco leitoso identificado com o símbolo de risco biológico.\n- GRUPO B (Químicos): Medicamentos vencidos, avariados ou produtos químicos de limpeza. Manter em recipientes resistentes a vazamentos e identificados. Medicamentos controlados devem ser descaracterizados conforme norma específica.\n- GRUPO D (Comuns): Papéis de escritório, embalagens secundárias, restos de alimentos. Descartar em saco plástico preto ou cinza.\n- GRUPO E (Perfurocortantes): Agulhas, ampolas de vidro quebradas, lancetas. Descartar em coletor rígido (Descarpack) específico, vedando ao atingir 2/3 da capacidade.\n\n2. ACONDICIONAMENTO E ARMAZENAMENTO TEMPORÁRIO:\n- Os sacos de lixo devem ser fechados quando atingirem 2/3 da capacidade ou pelo menos uma vez a cada 24 horas.\n- O lixo deve ser mantido em lixeiras com tampa acionada por pedal para evitar contato manual.\n- Transportar os resíduos para o abrigo externo utilizando carrinhos plásticos laváveis ou latas com tampa.\n\n3. ABRIGO EXTERNO E COLETA:\n- O abrigo externo deve ser de material lavável, possuir ralo conectado à rede de esgoto e ser mantido permanentemente trancado.\n- A coleta deve ser realizada apenas por empresas devidamente licenciadas pelo órgão ambiental competente.\n- O Farmacêutico deve conferir o Manifesto de Transporte de Resíduos (MTR) fornecido pela coletora.',
    monitoring: 'Auditoria mensal de pesagem de resíduos. Verificação semanal da limpeza do abrigo externo. Conferência bimestral do Certificado de Destinação Final (CDF).',
    reviewFrequency: 'Anual ou se houver alteração significativa no volume ou tipo de resíduos gerados.',
    references: 'RDC nº 222/2018 (ANVISA), Resolução CONAMA nº 358/2005.'
  },
  {
    id: 'pragas',
    title: 'Controle Integrado de Pragas e Vetores Urbanos',
    category: 'Sanitário',
    objective: 'Estabelecer medidas preventivas e corretivas para impedir a entrada, o abrigo e a proliferação de insetos e roedores na drogaria, mitigando riscos de contaminação e danos ao estoque.',
    applicationField: 'Toda a área interna e externa imediata da drogaria.',
    definitions: 'Praga: Insetos ou animais capazes de contaminar produtos. Desinsetização: Controle químico de insetos.',
    responsible: 'Farmacêutico RT e Empresa Especializada licenciada.',
    materials: 'Telas milimetradas, Iscas (externas), Cronograma de dedetização, Certificado de execução de serviço.',
    epi: 'Não aplicável ao funcionário (serviço terceirizado), mas exige desocupação da área por 6-12h.',
    riscos: 'Contaminação biológica por fezes/urina de roedores, destruição de embalagens secundárias, multas da vigilância sanitária.',
    procedure: '1. MEDIDAS PREVENTIVAS (BARREIRAS):\n- Manter ralos com grelhas de fechamento e sifonados.\n- Manter portas e janelas com vedação completa (rodinhos de borracha nas portas).\n- Evitar o acúmulo de caixas vazias e lixo em áreas internas.\n\n2. CONTROLE QUÍMICO TERCEIRIZADO:\n- Contratar empresa especializada licenciada pela Vigilância Sanitária.\n- Realizar a aplicação de praguicidas semestralmente ou em menor prazo se houver infestação.\n- Exigir o Certificado de Assistência Técnica após cada aplicação, contendo: Data, Pragas controladas, Produtos usados (Grupo Químico), Antídoto e validade do serviço.\n\n3. CUIDADOS PÓS-APLICAÇÃO:\n- Após o período de desocupação (geralmente 6h), realizar a limpeza úmida de todas as superfícies de contato antes de reabrir a drogaria.',
    monitoring: 'Inspeção visual semanal de pontos críticos (atrás de geladeiras e prateleiras). Auditoria semestral do prazo de validade do laudo de dedetização.',
    reviewFrequency: 'Anual.',
    references: 'RDC 44/2009, RDC 52/2009 (Controle de Vetores).'
  },
  {
    id: 'validade',
    title: 'Controle de Prazos de Validade e Qualidade do Estoque',
    category: 'Qualidade',
    objective: 'Estabelecer critérios rigorosos para o monitoramento sistemático dos prazos de validade, garantindo que nenhum produto vencido ou avariado permaneça no estoque comercializável ou na área de dispensação.',
    applicationField: 'Área de estoque (almoxarifado), prateleiras de autoatendimento e área de quarentena.',
    definitions: 'Vencimento: Data limite estabelecida pelo fabricante para o consumo seguro. PVPS: Primeiro que Vence, Primeiro que Sai.',
    responsible: 'Farmacêutico RT, Gerente e Auxiliares de Venda.',
    materials: 'Cronograma de inventário rotativo, Etiquetas coloridas de sinalização (Amarela/Vermelha), Planilha de controle de vencidos.',
    epi: 'Avental ou uniforme, sapatos fechados.',
    riscos: 'Dispensão de produto vencido (crime contra saúde pública), prejuízo financeiro, multas pesadas e interdição.',
    procedure: '1. PROCEDIMENTO DE CONFERÊNCIA SISTEMÁTICA:\n- Realizar conferência manual integral das prateleiras de dispensação e estoque no primeiro dia útil de cada mês.\n- Verificar lote e validade de cada caixa individualmente, não apenas da frente do estoque.\n\n2. SISTEMA DE ALERTAS VISUAIS:\n- Vencimento em 06 meses: Aplicar etiqueta AMARELA na embalagem secundária. Estes itens devem ser movidos para a frente da prateleira (sistema PVPS).\n- Vencimento em 03 meses: Aplicar etiqueta VERMELHA. Estes itens devem ser priorizados na venda ou oferecidos em promoções éticas se permitido.\n- Vencimento em 30 dias: Informar ao Farmacêutico para decisão de devolução ao fornecedor ou recolhimento preventivo.\n\n3. SEGREGAÇÃO E RETIRADA DE PRODUTOS VENCIDOS:\n- Produtos que atingiram a data de vencimento devem ser retirados IMEDIATAMENTE da área de venda.\n- Colocá-los na área de PRODUTOS VENCIDOS/AVARIADOS (segregada e trancada).\n- Registrar a retirada no sistema de gestão para baixa do estoque fiscal.\n\n4. DESTINAÇÃO FINAL:\n- Produtos vencidos devem ser encaminhados para incineração ou aterro sanitário licenciado através do Plano de Gerenciamento de Resíduos (PGRSS).',
    monitoring: 'Auditoria quinzenal aleatória em 03 seções do estoque. Verificação do relatório de "Controle de Lotes" do software mensalmente.',
    reviewFrequency: 'Anual.',
    references: 'RDC 44/2009 (ANVISA), Lei 8.078/1990 (Código de Defesa do Consumidor).'
  },
  {
    id: 'servicos_farmaceuticos',
    title: 'Aferição de Parâmetros Fisiológicos e Bioquímicos',
    category: 'Serviços',
    objective: 'Padronizar a prestação de serviços farmacêuticos de aferição de pressão arterial e glicemia capilar, garantindo resultados precisos e orientação adequada ao paciente para o autocuidado e prevenção de doenças, conforme a RDC 44/2009.',
    applicationField: 'Consultório Farmacêutico / Sala de Serviços.',
    definitions: 'Hipertensão: Pressão arterial persistentemente elevada. Glicemia Capilar: Medição do nível de glicose no sangue da ponta do dedo.',
    responsible: 'Farmacêutico devidamente treinado e habilitado.',
    materials: 'Esfigmomanômetro calibrado, Estetoscópio, Glicosímetro, Tiras-teste, Lancetas de segurança, Álcool 70%, Luvas de procedimento, Algodão, Declaração de Serviço Farmacêutico (DSF).',
    epi: 'Jaleco branco, luvas de procedimento, máscara (obrigatória para glicemia).',
    riscos: 'Contaminações por patógenos sanguíneos, erro de leitura por aparelho descalibrado, negligência em casos de valores críticos.',
    procedure: '1. PREPARAÇÃO DO AMBIENTE E DO PACIENTE:\n- O consultório deve garantir a privacidade do paciente.\n- O paciente deve estar em repouso de 5 a 10 minutos, em ambiente calmo e temperatura agradável.\n- Certificar-se de que o paciente não está com a bexiga cheia, não praticou exercícios físicos há 60 min, não ingeriu café, álcool ou fumou há 30 min.\n\n2. TÉCNICA DE AFERIÇÃO DA PRESSÃO ARTERIAL:\n- Posicionar o braço do paciente na altura do coração, com a palma da mão voltada para cima.\n- Selecionar a braçadeira de tamanho adequado ao braço.\n- Localizar a artéria braquial. Insuflar a braçadeira e realizar a desinsuflação lenta (2mmHg por segundo).\n- Identificar o primeiro som (Sistólica) e o último som (Diastólica). Repetir se necessário após 2 minutos.\n\n3. TÉCNICA DE MEDIÇÃO DE GLICEMIA CAPILAR:\n- Higienizar as mãos e calçar luvas.\n- Realizar a antissepsia da ponta do dedo do paciente (preferencialmente anelar ou médio).\n- Realizar a punção lateral do dedo com a lanceta. Descartar a primeira gota de sangue.\n- Colher a segunda gota na tira-teste inserida no glicosímetro. Aguardar o resultado.\n\n4. ORIENTAÇÃO E REGISTRO:\n- Emitir a DSF em duas vias (uma para o paciente, outra para a farmácia).\n- Explicar o significado dos valores encontrados sem realizar diagnóstico médico.\n- Se os valores estiverem alterados (crise hipertensiva ou hipo/hiperglicemia severa), encaminhar o paciente imediatamente ao serviço de urgência.',
    monitoring: 'Verificação mensal dos estoques de tiras e lancetas. Calibração anual documentada de todos os aparelhos de pressão.',
    reviewFrequency: 'Anual.',
    references: 'RDC 44/2009, VII Diretriz Brasileira de Hipertensão, Diretrizes da Sociedade Brasileira de Diabetes.'
  },
  {
    id: 'treinamento',
    title: 'Programa de Treinamento e Educação Continuada da Equipe',
    category: 'Gestão',
    objective: 'Assegurar que todos os colaboradores da drogaria possuam conhecimento técnico e operacional atualizado sobre as Boas Práticas Farmacêuticas, legislações vigentes e procedimentos internos de segurança.',
    applicationField: 'Todos os funcionários de todos os setores.',
    definitions: 'Capacitação: Processo de aquisição de habilidades específicas. Reciclagem: Atualização de conhecimentos já adquiridos.',
    responsible: 'Farmacêutico Responsável Técnico e Gerência Administrativa.',
    materials: 'Cronograma anual de treinamentos, Listas de presença assinadas, Material didático (slides, manuais, vídeos), Avaliações de eficácia.',
    epi: 'Identificação visível.',
    riscos: 'Execução de processos por equipe não capacitada, erros operacionais graves, acidentes de trabalho por desconhecimento.',
    procedure: '1. TREINAMENTO ADMISSIONAL (INTEGRAÇÃO):\n- Realizado no primeiro dia do colaborador. Conteúdo: Missão da empresa, Higienização das mãos, Uso de EPIs, Localização dos POPs e PGRSS.\n- O funcionário só poderá iniciar atividades técnicas após a conclusão desse módulo.\n\n2. TREINAMENTOS PERIÓDICOS (RECICLAGEM):\n- Realizar treinamentos coletivos trimestrais sobre temas críticos: Dispensação de Controlados, Atendimento ao Cliente, Práticas de Limpeza e Primeiros Socorros.\n- Realizar treinamento imediato sempre que houver atualização de um POP ou mudança na legislação sanitária.\n\n3. REGISTRO E COMPROVAÇÃO:\n- Cada treinamento deve gerar uma Ata de Treinamento contendo: Tema, Conteúdo programático, Carga horária, Nome e Assinatura dos participantes.\n\n4. AVALIAÇÃO DE RESULTADOS:\n- Aplicar questionário simples ao final do treinamento para verificar o aprendizado (Meta: 70% de acerto).',
    monitoring: 'Auditoria trimestral das pastas de treinamento. Verificação do cumprimento do cronograma anual (indicador de desempenho).',
    reviewFrequency: 'Anual.',
    references: 'RDC 44/2009 (ANVISA), Consolidação das Leis do Trabalho (CLT).'
  },
  {
    id: 'higienizacao_maos',
    title: 'Higienização das Mãos e Antissepsia Técnica',
    category: 'Sanitário',
    objective: 'Estabelecer a técnica correta de higienização das mãos para prevenir a contaminação cruzada e garantir a segurança do paciente em todos os serviços farmacêuticos prestados.',
    applicationField: 'Lavatórios de todas as áreas (Dispensa, Sala de aplicação e banheiros).',
    definitions: 'Fricção Antisséptica: Aplicação de álcool 70%. Lavagem Simples: Uso de água e sabonete comum.',
    responsible: 'Todos os profissionais e colaboradores sem exceção.',
    materials: 'Sabonete líquido neutro, Álcool etílico 70% (gel ou solução), Papel toalha de fibra virgem, Lixeira com pedal.',
    epi: 'Não aplicável.',
    riscos: 'Contaminação cruzada para pacientes e profissionais, disseminação de infecções hospitalares e comunitárias.',
    procedure: '1. TÉCNICA DE LAVAGEM COM ÁGUA E SABÃO (40-60 SEG):\n- Abrir a torneira e molhar as mãos, evitando tocar na pia.\n- Aplicar quantidade suficiente de sabonete líquido.\n- Friccionar as palmas, o dorso das mãos, os espaços interdigitais, os polegares e as pontas das unhas.\n- Enxaguar abundantemente. Secar com papel toalha descartável.\n- Utilizar o papel toalha para fechar a torneira se esta não for automática.\n\n2. TÉCNICA DE FRICÇÃO COM ÁLCOOL 70% (20-30 SEG):\n- Aplicar o produto na palma da mão e repetir os movimentos da lavagem até que o álcool seque naturalmente.\n\n3. MOMENTOS OBRIGATÓRIOS:\n- Antes e após o contato com qualquer paciente.\n- Antes de realizar qualquer procedimento asséptico (Aplicação de injetáveis).\n- Após o contato com fluidos corporais ou superfícies próximas ao paciente.\n- Após remover luvas de procedimento.',
    monitoring: 'Verificação diária do abastecimento de insumos (sabão/papel). Auditoria observacional mensal da adesão técnica pela equipe.',
    reviewFrequency: 'Anual.',
    references: 'Protocolo de Higiene das Mãos da OMS, RDC 42/2010 (ANVISA).'
  },
  {
    id: 'falta_energia',
    title: 'Procedimento em Caso de Falta de Energia Elétrica',
    category: 'Logística',
    objective: 'Garantir a manutenção da cadeia de frio para medicamentos termolábeis durante interrupções de energia.',
    applicationField: 'Geladeira de termolábeis.',
    definitions: 'Cadeia de Frio: Sistema de conservação de produtos sensíveis.',
    responsible: 'Farmacêutico e Auxiliar Responsável.',
    materials: 'Isopor (caixas térmicas), Gelox reserva, Termômetro de máxima e mínima.',
    epi: 'Jaleco, luvas de proteção térmica (se necessário para manuseio de gelo seco/gelox).',
    riscos: 'Perda total de estoque termolábil, administração de medicamento ineficaz ao paciente por quebra na cadeia de frio.',
    procedure: '1. IMEDIATO:\n- NÃO abrir a geladeira desnecessariamente.\n- Verificar previsão de retorno com a concessionária.\n\n2. APÓS 30 MINUTOS:\n- Transferir produtos para caixas térmicas com gelox preparado.\n- Monitorar temperatura da caixa a cada hora.\n\n3. RETORNO:\n- Aguardar geladeira atingir 2°C-8°C antes de retornar os produtos.',
    monitoring: 'Registro de ocorrências em planilha específica.',
    reviewFrequency: 'Anual.',
    references: 'Manual de Rede de Frio (MS).'
  },
  {
    id: 'devolucao',
    title: 'Devolução de Mercadorias ao Fornecedor',
    category: 'Logística',
    objective: 'Padronizar o fluxo de retorno de produtos por desvio de qualidade, validade ou erro no pedido.',
    applicationField: 'Setor de compras e expedição.',
    definitions: 'Nota Fiscal de Devolução: Documento que acompanha a mercadoria de volta.',
    responsible: 'Gerente e Farmacêutico RT.',
    materials: 'Nota Fiscal, Sistema de Gestão.',
    epi: 'Crachá de identificação.',
    riscos: 'Falhas na gestão de estoque, prejuízo financeiro por erros de lançamento.',
    procedure: '1. IDENTIFICAÇÃO:\n- Separar itens para devolução em área segregada.\n\n2. DOCUMENTAÇÃO:\n- Emitir NF de devolução citando a NF de origem.\n\n3. COLETA:\n- Conferir itens com o motorista e coletar comprovante de entrega.',
    monitoring: 'Conferência mensal de notas fiscais de devolução.',
    reviewFrequency: 'Anual.',
    references: 'Legislação Fiscal e Sanitária Vigente.'
  },
  {
    id: 'recolhimento',
    title: 'Recolhimento de Produtos (Recall)',
    category: 'Qualidade',
    objective: 'Padronizar as ações para retirada rápida e eficiente de produtos do mercado em caso de risco à saúde.',
    applicationField: 'Estoque e área de vendas.',
    definitions: 'Recall: Procedimento de retirada de circulação de um produto.',
    responsible: 'Farmacêutico RT.',
    materials: 'Acesso ao site da ANVISA, Lista de contatos de clientes.',
    epi: 'Identificação visível.',
    riscos: 'Uso de lotes perigosos por pacientes, danos à reputação e multas graves.',
    procedure: '1. RECEBIMENTO DO ALERTA:\n- Identificar produtos suspensos via RE (Resolução) da ANVISA.\n\n2. SEGREGAÇÃO:\n- Retirar imediatamente do estoque e área de venda.\n- Colocar em área de "PRODUTOS CONTROLADOS/SUSPENSOS".\n\n3. NOTIFICAÇÃO:\n- Informar ao fornecedor e registrar as quantidades em estoque.\n\n4. RASTREABILIDADE:\n- Verificar no sistema se houve vendas recentes do lote e, se possível, alertar os clientes.',
    monitoring: 'Auditoria trimestral do sistema de alertas da ANVISA.',
    reviewFrequency: 'Anual.',
    references: 'RDC 055/2005.'
  },
  {
    id: 'farmacovigilancia',
    title: 'Sistema de Farmacovigilância e Queixas Técnicas',
    category: 'Qualidade',
    objective: 'Estabelecer rotinas para identificação e notificação de eventos adversos ou desvios de qualidade.',
    applicationField: 'Atendimento ao cliente e suporte técnico.',
    definitions: 'RAM: Reação Adversa. NOTIVISA: Sistema eletrônico da ANVISA.',
    responsible: 'Farmacêutico RT.',
    materials: 'Formulários de registro, Acesso ao portal NOTIVISA.',
    epi: 'Identificação visível.',
    riscos: 'Sub-notificação de eventos graves, desconhecimento de novos efeitos colaterais de fármacos.',
    procedure: '1. DETECÇÃO:\n- Coletar dados do paciente e do produto (Lote/Fab) ao receber relato de RAM ou defeito.\n\n2. NOTIFICAÇÃO:\n- Avaliar gravidade e notificar no sistema NOTIVISA em até 15 dias (72h para óbitos ou ameaça à vida).',
    monitoring: 'Acompanhamento do histórico de notificações e respostas da vigilância sanitiária.',
    reviewFrequency: 'Anual.',
    references: 'RDC nº 04/2009, RDC nº 67/2007.'
  },
  {
    id: 'sngpc',
    title: 'Escrituração e Transmissão de Dados ao SNGPC (ANVISA)',
    category: 'Gestão',
    objective: 'Padronizar a escrituração eletrônica e a transmissão de dados referentes à movimentação de medicamentos sujeitos a controle especial e antimicrobianos, garantindo a rastreabilidade e o cumprimento dos prazos estabelecidos pela ANVISA.',
    applicationField: 'Computador do Farmacêutico e Sistema de Gestão da Drogaria.',
    definitions: 'SNGPC: Sistema Nacional de Gerenciamento de Produtos Controlados. XML: Formato de arquivo para transferência de dados.',
    responsible: 'Farmacêutico Responsável Técnico (RT). Os dados de acesso ao portal são de uso pessoal e intransferível do RT.',
    materials: 'Computador com acesso à internet estável, Certificado Digital tipo A1 ou A3, Software de farmácia homologado pela ANVISA, Receitas e Notificações retidas.',
    epi: 'Crachá de identificação de Responsável Técnico.',
    riscos: 'Penalidades criminais por erro de escrituração, suspensão da licença, perda de prazos legais.',
    procedure: '1. CONFERÊNCIA E DIGITAÇÃO DIÁRIA:\n- Ao final de cada turno, conferir todas as receitas retidas com os lançamentos efetuados no sistema.\n- Verificar se não há erros de digitação de CRM, Lote ou CPF do comprador.\n- No caso de Notas Fiscais de entrada, conferir se os lotes importados coincidem com o produto físico.\n\n2. GERAÇÃO DO ARQUIVO DE TRANSMISSÃO:\n- O sistema deve gerar o arquivo XML abrangendo o período de movimentação (mínimo 1 dia, máximo 7 dias).\n- O arquivo deve conter: Entradas (compras/transferências), Saídas (vendas/devoluções/perdas).\n\n3. TRANSMISSÃO AO PORTAL ANVISA:\n- Acessar o site do SNGPC através do navegador configurado para uso do certificado digital.\n- Realizar o upload do arquivo XML gerado.\n- Aguardar a mensagem de confirmação de recebimento pelo servidor da ANVISA.\n\n4. MONITORAMENTO DE ERROS E ACEITE:\n- Consultar o "Status da Transmissão" decorridas 24 horas do envio.\n- Status "Aceito": Imprimir o comprovante e arquivar em pasta específica.\n- Status "Rejeitado": Analisar o código de erro, corrigir os dados no sistema de gestão e retransmitir imediatamente.',
    monitoring: 'Verificação semanal do saldo físico do armário vs. saldo virtual no SNGPC. Auditoria mensal dos comprovantes de aceite.',
    reviewFrequency: 'Anual ou em caso de mudanças no cronograma de transmissão da ANVISA.',
    references: 'RDC nº 22/2011, RDC nº 58/2007, RDC nº 20/2011.'
  },
  {
    id: 'limpeza_geladeira',
    title: 'Higienização e Degelo de Geladeira de Termolábeis',
    category: 'Sanitário',
    objective: 'Estabelecer a rotina de limpeza e manutenção preventiva da geladeira de medicamentos, garantindo a higiene interna e o funcionamento eficiente do sistema de refrigeração.',
    applicationField: 'Geladeira técnica de uso exclusivo para medicamentos.',
    definitions: 'Capa de Gelo: Acúmulo de gelo nas paredes que atua como isolante térmico negativo.',
    responsible: 'Auxiliar de Farmácia sob supervisão e conferência do Farmacêutico.',
    materials: 'Caixas térmicas devidamente preparadas (2°C a 8°C), Bobinas de gelo reciclável, Termômetro de máxima e mínima, Pano limpo, Sabão neutro ou solução de limpeza indicada pelo fabricante.',
    epi: 'Luvas de proteção, jaleco.',
    riscos: 'Quebra da cadeia de frio, choque elétrico, quebra de frascos de insulina ou vacinas.',
    procedure: '1. PREPARAÇÃO E SEGURANÇA DOS PRODUTOS:\n- Realizar o procedimento no primeiro horário da manhã, quando a temperatura ambiente costuma ser menor.\n- Transferir todos os medicamentos para caixas térmicas com gelox, monitorando a temperatura durante todo o processo (deve permanecer entre 2°C e 8°C).\n- Desligar o equipamento da rede elétrica e sinalizar "EQUIPAMENTO EM MANUTENÇÃO".\n\n2. DEGELO E LIMPEZA INTERNA:\n- Abrir as portas e aguardar o degelo natural do congelador (NUNCA usar objetos pontiagudos ou secador de cabelo).\n- Retirar as prateleiras e gavetas. Lavá-las com água e sabão neutro.\n- Limpar o interior da geladeira com pano levemente úmido. Secar completamente todas as superfícies.\n\n3. REATIVAÇÃO E REESTOCAGEM:\n- Ligar o equipamento e aguardar o ciclo de refrigeração atingir a faixa de 2°C a 8°C.\n- Repor os medicamentos organizadamente, deixando espaço para circulação de ar nas laterais.',
    monitoring: 'Registro mensal na Planilha de Manutenção de Equipamentos. Inspeção quinzenal visual do acúmulo de gelo.',
    reviewFrequency: 'Anual.',
    references: 'Manual de Rede de Frio (MS), Manual do Fabricante do Equipamento.'
  },
  {
    id: 'atendimento_fiscal',
    title: 'Protocolo de Atendimento à Fiscalização Sanitária e do CRF',
    category: 'Gestão',
    objective: 'Padronizar o atendimento aos órgãos de fiscalização (ANVISA/VISA/CRF/PF), garantindo segurança jurídica, transparência e organização durante o processo de inspeção.',
    applicationField: 'Toda a unidade da drogaria.',
    definitions: 'Auto de Infração: Documento que relata irregularidades. Termo de Visita: Registro de rotina do conselho profissional.',
    responsible: 'Farmacêutico Responsável Técnico, Gerente da Unidade ou Farmacêutico Substituto.',
    materials: 'Pasta de Documentação Legal (Alvará, Licença Sanitária, CNPJ, CTPS, POPs, PGRSS, PCMSO/PPRA), Carimbos.',
    epi: 'Identificação visível e crachá funcional.',
    riscos: 'Multas por falta de documentação acessível, interdição do estabelecimento, cassação da licença.',
    procedure: '1. RECEPÇÃO E IDENTIFICAÇÃO:\n- Solicitar a identificação funcional (carteira de fiscal) e a finalidade da visita.\n- Encaminhar os fiscais para área administrativa ou consultório para início dos trabalhos.\n- Notificar imediatamente o RT ou proprietário se estes não estiverem presentes.\n\n2. APRESENTAÇÃO DOCUMENTAL:\n- Disponibilizar prontamente a Pasta de Documentação Legal.\n- Apresentar os Livros de Registro e o acesso ao SNGPC se solicitado.\n- Demonstrar a organização do estoque e as planilhas de controle de temperatura/umidade de modo proativo.\n\n3. CONDUÇÃO DA INSPEÇÃO:\n- Acompanhar o fiscal em todos os setores de modo colaborativo.\n- Responder às dúvidas de forma técnica e objetiva. Não fornecer informações incertas.\n\n4. ENCERRAMENTO E PROVIDÊNCIAS:\n- Ler atentamente o Termo de Inspeção ou Auto de Visita. Se houver exigências, solicitar prazo razoável para cumprimento.\n- Assinar e carimbar o documento. Arquivar cópia legível na pasta de fiscalização.',
    monitoring: 'Auditoria trimestral da validade de todas as licenças e certidões negativas de débito.',
    reviewFrequency: 'Anual.',
    references: 'Lei nº 6.437/77, RDC nº 44/2009, Resoluções Regionais do CRF.'
  },
];
